#!/usr/bin/env python
import argparse
import glob
import re
import requests
import webbrowser


parser = argparse.ArgumentParser(description="project euler runner")
parser.add_argument(
    "-s",
    "--solve",
    dest="solve",
    type=int,
    required=False,
    nargs=1,
    action="store",
    help="solve problem with given number",
)

parser.add_argument(
    "-v",
    "--verbose",
    dest="verbose",
    action="store_true",
    required=False,
    help="print verbose result",
)

parser.add_argument(
    "-p",
    "--prepare",
    dest="prepare",
    type=int,
    required=False,
    nargs=1,
    action="store",
    help="prepare file for given problem number",
)

parser.add_argument(
    "-o",
    "--open",
    dest="open",
    type=int,
    action="store",
    required=False,
    nargs=1,
    help="print verbose result",
)

args = parser.parse_args()

if args.solve:
    file = glob.glob(f"problems/p{args.solve[0]}.py")
    if len(file) > 1:
        parser.error("Multiple files found. Exiting...")

    problem = __import__(
        file[0].split(".")[0].replace("/", "."), fromlist=[None]  # type: ignore
    ).Main

    problem.solve(verbose=args.verbose)


if args.prepare:
    problem = re.search(
        r'<div class="problem_content" role="problem">((.*\s)*?)</div>',
        requests.get(f"https://projecteuler.net/problem={args.prepare[0]}").text,
    )
    paragraphs = re.findall(r"<p.*?>(.+)</p>", problem.group(1))

    with open(f"problems/p{args.prepare[0]}.py", "w") as template, open(
        "fwk/_template.py", "r"
    ) as _template:
        template.write(f"# Problem number {args.prepare[0]}.\n#\n# ")
        for paragraph in paragraphs:
            counter = 2
            for word in paragraph.split(" "):
                if counter + len(word) > 88:
                    counter = 3 + len(word)
                    template.write(f"\n# {word} ")
                else:
                    counter += len(word)
                    template.write(word)
                    if counter < 88 and word != paragraph.split(" ")[-1]:
                        template.write(" ")
                        counter += 1
            template.write("\n")
            if not paragraph == paragraphs[-1]:
                template.write("#\n# ")

        for line in _template.readlines():
            template.write(line.replace("# type: ignore", "").rstrip() + "\n")

if args.open:
    webbrowser.open(f"https://projecteuler.net/problem={args.open[0]}")
